package br.com.teste.cadastro.config;

/**
 * Enum com os código de exceções/mensagens.
 */
public enum MessageCode {

	SUCESSO_SALVAR_CLIENTE("MSG-SUCESSO-SALVAR-CLIENTE"),
	SUCESSO_ALTERAR_CLIENTE("MSG-SUCESSO-ALTERAR-CLIENTE"),
	SUCESSO_EXCLUIR_CLIENTE("MSG-SUCESSO-EXCLUIR-CLIENTE"),
	FALHA_SALVAR_CLIENTE("MSG-FALHA-SALVAR-CLIENTE"),
	FALHA_ALTERAR_CLIENTE("MSG-FALHA-ALTERAR-CLIENTE"),
	FALHA_EXCLUIR_CLIENTE("MSG-FALHA-EXCLUIR-CLIENTE"),
	CLIENTE_NAO_SALVO("MSG-CLIENTE-NAO-SALVO"),
	CLIENTE_NAO_ATUALIZADO("MSG-CLIENTE-NAO-ATUALIZADO"),
	FALHA_RECUPERAR_CLIENTES("MSG-FALHA-RECUPERAR-CLIENTES"),
	CLIENTES_NAO_ENCONTRADOS("MSG-CLIENTES-NAO-ENCONTRADOS"),
	FALHA_RECUPERAR_CLIENTE("MSG-FALHA-RECUPERAR-CLIENTE"),
	CLIENTE_NAO_ENCONTRADO("MSG-CLIENTE-NAO-ENCONTRADO"),
	PARAMETROS_OBRIGATORIOS("MSG-PARAMETROS-OBRIGATORIOS"),
	CLIENTE_NAO_FORNECIDO("MSG-CLIENTE-NAO-FORNECIDO");

	private final String chave;

	/**
	 * Construtor do Enum.
	 *
	 * @param chave
	 */
	MessageCode(String chave) {
		this.chave = chave;
	}

	@Override
	public String toString() {
		return chave;
	}
}
